import './advanced-settings010.css';

type P={topK:number;setTopK:(v:number)=>void;minP:number;setMinP:(v:number)=>void;repeatPenalty:number;setRepeatPenalty:(v:number)=>void;seed:number;setSeed:(v:number)=>void;keepAlive:string;setKeepAlive:(v:string)=>void;canThink:boolean;thinking:boolean};
type Preset='balanced'|'reproducible'|'creative'|'memory';
export default function AdvancedSettings010(p:P){
 function preset(x:Preset){
  if(x==='balanced'){p.setTopK(40);p.setMinP(.05);p.setRepeatPenalty(1.1);p.setSeed(-1);p.setKeepAlive('5m')}
  if(x==='reproducible'){p.setTopK(40);p.setMinP(.05);p.setRepeatPenalty(1.1);p.setSeed(42);p.setKeepAlive('5m')}
  if(x==='creative'){p.setTopK(100);p.setMinP(.02);p.setRepeatPenalty(1.05);p.setSeed(-1);p.setKeepAlive('15m')}
  if(x==='memory'){p.setTopK(30);p.setMinP(.08);p.setRepeatPenalty(1.12);p.setSeed(-1);p.setKeepAlive('0')}
 }
 return <section className="adv10"><div className="adv10-head"><div><span>ADVANCED MODEL SETTINGS</span><h3>Sampling, reproducibility and residency</h3></div><small>{p.canThink?p.thinking?'Thinking enabled':'Thinking supported':'Thinking unavailable for this model'}</small></div><div className="adv10-presets"><span>Presets</span><button onClick={()=>preset('balanced')}>Balanced</button><button onClick={()=>preset('reproducible')}>Reproducible</button><button onClick={()=>preset('creative')}>Creative</button><button onClick={()=>preset('memory')}>Low residency</button></div><div className="adv10-grid"><label><span>Top K <b>{p.topK}</b></span><input type="range" min="1" max="200" value={p.topK} onChange={e=>p.setTopK(Number(e.target.value))}/><small>Restricts each token step to the K most likely choices.</small></label><label><span>Min P <b>{p.minP.toFixed(2)}</b></span><input type="range" min="0" max="0.5" step="0.01" value={p.minP} onChange={e=>p.setMinP(Number(e.target.value))}/><small>Filters very unlikely tokens relative to the current best token.</small></label><label><span>Repeat penalty <b>{p.repeatPenalty.toFixed(2)}</b></span><input type="range" min="0.8" max="1.5" step="0.01" value={p.repeatPenalty} onChange={e=>p.setRepeatPenalty(Number(e.target.value))}/><small>Higher values discourage repetitive generations.</small></label><label><span>Seed</span><input type="number" value={p.seed} onChange={e=>p.setSeed(Number(e.target.value))}/><small>Use -1 for normal random behavior; fixed non-negative values improve reproducibility.</small></label><label><span>Keep model loaded</span><select value={p.keepAlive} onChange={e=>p.setKeepAlive(e.target.value)}><option value="0">Unload after response</option><option value="1m">1 minute</option><option value="5m">5 minutes</option><option value="15m">15 minutes</option><option value="30m">30 minutes</option><option value="1h">1 hour</option></select><small>Controls how long Ollama keeps the model resident after generation.</small></label></div><p className="adv10-note">Presets only change the controls shown here; they never install models or alter system settings. Context, temperature, Top P, maximum output and Thinking stay in the primary controls. These advanced values are sent to the same local Ollama request and can affect speed, memory use and output style.</p></section>}
