import { useEffect, useMemo, useRef, useState } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { listen } from '@tauri-apps/api/event';

type Mode='bundled'|'external'; type Tab='overview'|'models'|'lab'|'library'|'developer';
type Profile={os:string;arch:string;chip:string;memoryBytes:number;logicalCores:number;freeStorageBytes:number};
type OllamaModel={name:string;model?:string;size:number;modified_at?:string;details?:{parameter_size?:string;quantization_level?:string;family?:string}};
type Pull={model:string;status:string;percent?:number;done:boolean;cancelled:boolean;error?:string};
type HfModel={id:string;downloads?:number;likes?:number;tags?:string[];cardData?:{license?:string}};
type Variant={filename:string;size:number;quantization:string;sha256?:string;sourceUrl:string};
type ImportEvent={importId:string;repoId:string;filename:string;model:string;stage:string;status:string;percent?:number;done:boolean;cancelled:boolean;error?:string;sha256?:string};

const GB=1024**3; const fmt=(n=0)=>n?`${(n/GB).toFixed(n>10*GB?1:2)} GB`:'—';
const api=(mode:Mode,method:string,path:string,body?:unknown)=>invoke<any>('ollama_json',{mode,method,path,body:body??null});
function fit(size:number,memory:number){if(!size||!memory)return{score:70,label:'Unknown'};const r=size/memory;const score=Math.max(20,Math.min(99,Math.round(104-r*70)));return{score,label:r<.48?'Excellent':r<.66?'Recommended':r<.82?'Heavy':'Not ideal'}}
function qRank(q:string){return ({Q2_K:2,Q3_K_M:3,Q4_0:4,Q4_K_S:4.2,Q4_K_M:4.5,Q5_K_S:5,Q5_K_M:5.4,Q6_K:6,Q8_0:8,F16:16,BF16:16} as Record<string,number>)[q]??4}
function recommendation(v:Variant[],memory:number){return [...v].sort((a,b)=>{const af=fit(a.size,memory).score,bf=fit(b.size,memory).score;const as=af>=70?100+qRank(a.quantization):af,bs=bf>=70?100+qRank(b.quantization):bf;return bs-as})[0]?.filename}

export default function App(){
 const modeRef=useRef<Mode>('bundled');
 const [tab,setTab]=useState<Tab>('overview'),[mode,setMode]=useState<Mode>('bundled'),[profile,setProfile]=useState<Profile|null>(null),[online,setOnline]=useState(false),[version,setVersion]=useState(''),[models,setModels]=useState<OllamaModel[]>([]),[selected,setSelected]=useState(''),[notice,setNotice]=useState('');
 const [pullName,setPullName]=useState(''),[pulls,setPulls]=useState<Record<string,Pull>>({});
 const [hfQuery,setHfQuery]=useState('qwen gguf'),[hf,setHf]=useState<HfModel[]>([]),[hfSelected,setHfSelected]=useState<HfModel|null>(null),[variants,setVariants]=useState<Variant[]>([]),[imports,setImports]=useState<Record<string,ImportEvent>>({}),[busy,setBusy]=useState(false);
 const [ctx,setCtx]=useState(8192),[temp,setTemp]=useState(.7),[topP,setTopP]=useState(.9),[maxOut,setMaxOut]=useState(512),[system,setSystem]=useState('You are a concise, accurate local assistant.'),[prompt,setPrompt]=useState('Explain why local inference can be private.'),[answer,setAnswer]=useState(''),[speed,setSpeed]=useState<number|null>(null),[thinking,setThinking]=useState(false);
 const memory=profile?.memoryBytes??0; const best=useMemo(()=>[...models].sort((a,b)=>fit(b.size,memory).score-fit(a.size,memory).score)[0],[models,memory]);
 async function refresh(which:Mode=modeRef.current){try{const [v,t]=await Promise.all([api(which,'GET','/api/version'),api(which,'GET','/api/tags')]);setOnline(true);setVersion(v.version??'');setModels(t.models??[]);if(!selected&&t.models?.[0])setSelected(t.models[0].name)}catch(e){setOnline(false);setNotice(String(e))}}
 async function switchMode(next:Mode){modeRef.current=next;setMode(next);setNotice('');if(next==='bundled'){try{await invoke('start_bundled_ollama');setTimeout(refresh,700)}catch(e){setNotice(String(e))}}else{try{await invoke('stop_bundled_ollama')}catch{}setTimeout(refresh,150)}}
 useEffect(()=>{invoke<Profile>('system_profile').then(setProfile).catch(e=>setNotice(String(e)));switchMode('bundled');const unsubs:Promise<()=>void>[]=[];unsubs.push(listen<Pull>('modeldock://pull-progress',e=>{setPulls(p=>({...p,[e.payload.model]:e.payload}));if(e.payload.done&&!e.payload.error)refresh()}));unsubs.push(listen<ImportEvent>('modeldock://import-progress',e=>{setImports(p=>({...p,[e.payload.importId]:e.payload}));if(e.payload.done&&!e.payload.error)refresh()}));return()=>{unsubs.forEach(p=>p.then(f=>f()))}},[]);
 async function run(){if(!selected)return;setBusy(true);setAnswer('');setSpeed(null);const started=performance.now();try{const r=await api(mode,'POST','/api/chat',{model:selected,messages:[{role:'system',content:system},{role:'user',content:prompt}],stream:false,think:thinking,options:{num_ctx:ctx,temperature:temp,top_p:topP,num_predict:maxOut}});setAnswer(r.message?.content||r.response||'');const evalCount=r.eval_count??0,evalDuration=r.eval_duration??0;setSpeed(evalDuration?evalCount/(evalDuration/1e9):evalCount/((performance.now()-started)/1000))}catch(e){setAnswer(`Error: ${e}`)}finally{setBusy(false)}}
 async function pull(){const name=pullName.trim();if(!name)return;setPulls(p=>({...p,[name]:{model:name,status:'Starting',done:false,cancelled:false}}));invoke('pull_model',{mode,model:name}).catch(e=>setPulls(p=>({...p,[name]:{model:name,status:'Failed',done:true,cancelled:false,error:String(e)}})))}
 async function searchHf(){setBusy(true);try{const r=await invoke<any[]>('search_huggingface',{query:hfQuery,limit:30});setHf(r as HfModel[])}catch(e){setNotice(String(e))}finally{setBusy(false)}}
 async function inspect(m:HfModel){setHfSelected(m);setVariants([]);try{setVariants(await invoke<Variant[]>('list_hf_gguf_variants',{repoId:m.id}))}catch(e){setNotice(String(e))}}
 async function importVariant(v:Variant){if(!hfSelected)return;const model=`${hfSelected.id.split('/').pop()}:${v.quantization.toLowerCase().replaceAll('_','-')}`;const id=`${hfSelected.id}:${v.filename}`;setImports(p=>({...p,[id]:{importId:id,repoId:hfSelected.id,filename:v.filename,model,stage:'start',status:'Starting',done:false,cancelled:false}}));invoke('import_hf_gguf',{mode,repoId:hfSelected.id,filename:v.filename,model,license:hfSelected.cardData?.license??null,expectedSha256:v.sha256??null}).catch(e=>setImports(p=>({...p,[id]:{...p[id],done:true,error:String(e),status:'Failed'}})))}
 async function remove(name:string){if(!confirm(`Delete ${name}?`))return;try{await api(mode,'DELETE','/api/delete',{model:name});await refresh()}catch(e){setNotice(String(e))}}
 const snippet=`const response = await fetch('http://127.0.0.1:${mode==='bundled'?'11435':'11434'}/api/chat', {\n  method: 'POST',\n  headers: {'Content-Type':'application/json'},\n  body: JSON.stringify({model: '${selected||'your-model'}', messages: [{role:'user', content:'Hello'}], stream: false})\n});\nconsole.log(await response.json());`;
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">M</div>ModelDock</div>{(['overview','models','lab','library','developer'] as Tab[]).map(t=><button key={t} className={`nav-label ${tab===t?'nav-active':''}`} onClick={()=>setTab(t)}>{({overview:'Overview',models:'My Models',lab:'Model Lab',library:'Library',developer:'Developer'} as any)[t]}</button>)}<div className="sidebar-spacer"/><div className="machine-card"><div className="machine-title">{profile?.chip||'Detecting hardware'}</div><div className="tiny-row"><span>Memory</span><b>{fmt(memory)}</b></div><div className="tiny-row"><span>Free storage</span><b>{fmt(profile?.freeStorageBytes)}</b></div><div className="engine-switch"><button className={mode==='bundled'?'active':''} onClick={()=>switchMode('bundled')}>Bundled</button><button className={mode==='external'?'active':''} onClick={()=>switchMode('external')}>External</button></div></div></aside>
 <main className="main"><header className="header"><h1>Local Model Control Center <span className="muted small">Alpha 0.5</span></h1><div className="header-actions"><span className={`connection-pill ${online?'ok':'off'}`}>{online?`Ollama ${version}`:'Engine offline'}</span><button className="ghost" onClick={refresh}>Refresh</button></div></header><div className="page">{notice&&<div className="notice" onClick={()=>setNotice('')}>{notice}</div>}
 {tab==='overview'&&<><div className="hero-grid"><section className="hero-card"><div className="eyebrow">Desktop-only · bundled local runtime</div><h2>Find, fit, tune, benchmark, build.</h2><p className="muted">ModelDock keeps local-model setup visual while preserving direct access to Ollama and community GGUF models.</p><div className="engine-path">ModelDock → Rust/Tauri → {mode==='bundled'?'Bundled Ollama :11435':'External Ollama :11434'} → Metal / CPU</div>{best&&<div className="recommendation"><div className="recommendation-icon">★</div><div><b>Best installed fit</b><div>{best.name}</div></div><div className="score">{fit(best.size,memory).score}</div></div>}</section><section className="resource-card"><div className="card-title">This computer</div><div className="metric">{fmt(memory)}</div><div className="muted">{profile?.arch} · {profile?.logicalCores} logical cores</div><div className="quick-stats"><div className="stat-card">Models<b>{models.length}</b></div><div className="stat-card">Storage<b>{fmt(models.reduce((s,m)=>s+m.size,0))}</b></div><div className="stat-card">Free<b>{fmt(profile?.freeStorageBytes)}</b></div></div></section></div><div className="section-title">Installed models</div><div className="model-grid">{models.slice(0,8).map(m=><div className="model-card" key={m.name}><div className="model-top"><div><b>{m.name}</b><div className="muted small">{m.details?.parameter_size||'Unknown'} · {m.details?.quantization_level||'—'}</div></div><span className={`fit-badge ${fit(m.size,memory).score>69?'good':'bad'}`}>{fit(m.size,memory).label}</span></div><div className="fit-line"><span>{fmt(m.size)}</span><b>{fit(m.size,memory).score}/100</b></div><div className="progress"><i style={{width:`${fit(m.size,memory).score}%`}}/></div></div>)}</div></>}
 {tab==='models'&&<div className="two-column"><section><div className="section-title compact">Installed</div><div className="stack">{models.map(m=><button className={`model-row ${selected===m.name?'selected':''}`} key={m.name} onClick={()=>setSelected(m.name)}><div className="model-main"><b>{m.name}</b><small>{fmt(m.size)} · {m.details?.quantization_level||'—'}</small></div><span className={`fit-badge ${fit(m.size,memory).score>69?'good':'bad'}`}>{fit(m.size,memory).score}</span></button>)}</div></section><section className="inspector">{selected?(()=>{const m=models.find(x=>x.name===selected);return m?<><div className="inspector-head"><div><div className="eyebrow">Model Passport</div><h2>{m.name}</h2></div><div className="big-avatar">AI</div></div><div className="fit-panel">Hardware fit <b>{fit(m.size,memory).score}/100 · {fit(m.size,memory).label}</b></div><div className="spec-grid"><div className="spec">Disk<b>{fmt(m.size)}</b></div><div className="spec">Parameters<b>{m.details?.parameter_size||'—'}</b></div><div className="spec">Quantization<b>{m.details?.quantization_level||'—'}</b></div></div><div className="inspector-actions"><button className="primary" onClick={()=>setTab('lab')}>Open in Lab</button><button className="danger" onClick={()=>remove(m.name)}>Delete</button></div></>:null})():<div className="muted">Select a model.</div>}</section></div>}
 {tab==='lab'&&<div className="lab-layout"><section className="controls-card"><div className="section-title compact">Visual parameters</div><label className="select-label">Model<select value={selected} onChange={e=>setSelected(e.target.value)}>{models.map(m=><option key={m.name}>{m.name}</option>)}</select></label><textarea className="system-input" value={system} onChange={e=>setSystem(e.target.value)}/>{[["Context",ctx,2048,32768,1024,setCtx],["Temperature",temp,0,2,.05,setTemp],["Top P",topP,.1,1,.05,setTopP],["Max output",maxOut,64,2048,64,setMaxOut]].map(([label,val,min,max,step,setter]:any)=><div className="slider-block" key={label}><div className="slider-head"><span>{label}</span><b>{val}</b></div><input type="range" value={val} min={min} max={max} step={step} onChange={e=>setter(Number(e.target.value))}/></div>)}<div className="toggle-row"><span>Thinking mode</span><button className={thinking?'on':''} onClick={()=>setThinking(!thinking)}/></div></section><section className="playground-card"><div className="playground-top"><div><b>Prompt test</b><div className="muted small">Real local inference</div></div>{speed!==null&&<span className="speed-chip">{speed.toFixed(1)} tok/s</span>}</div><div className={`response ${!answer?'response-empty':''}`}>{answer||'Run a prompt to benchmark this model.'}</div><div className="prompt-row"><textarea value={prompt} onChange={e=>setPrompt(e.target.value)}/><button className="send" disabled={busy||!selected} onClick={run}>{busy?'Running…':'Run'}</button></div></section></div>}
 {tab==='library'&&<><div className="library-hero"><div className="eyebrow">Unified Model Library I + II</div><h2>Ollama + Hugging Face GGUF</h2><p className="muted">Install registry models directly or inspect, verify and import community GGUF variants.</p></div><div className="library-columns"><section className="library-panel"><div className="panel-head"><h3>Ollama Direct</h3><span className="muted small">real pull</span></div><div className="install-box"><input value={pullName} onChange={e=>setPullName(e.target.value)} placeholder="qwen3:8b"/><button className="primary" onClick={pull}>Install</button></div><div className="download-list">{Object.values(pulls).map(p=><div className="download-task" key={p.model}><div><b>{p.model}</b><div className={`task-state ${p.error?'error':p.done?'done':''}`}>{p.error||p.status}</div></div>{!p.done&&<button className="ghost" onClick={()=>invoke('cancel_pull',{model:p.model})}>Cancel</button>}<div className="download-progress"><i style={{width:`${p.percent??0}%`}}/></div></div>)}</div></section><section className="library-panel"><div className="panel-head"><h3>Hugging Face GGUF</h3><span className="muted small">source-aware import</span></div><div className="install-box"><input value={hfQuery} onChange={e=>setHfQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&searchHf()}/><button className="primary" onClick={searchHf}>Search</button></div><div className="hf-browser"><div className="hf-list">{hf.map(m=><div className={`hf-row ${hfSelected?.id===m.id?'selected':''}`} key={m.id} onClick={()=>inspect(m)}><div className="model-main"><b>{m.id}</b><small>{(m.downloads??0).toLocaleString()} downloads · {m.cardData?.license||'license unspecified'}</small></div></div>)}</div><div className="variant-panel">{hfSelected?<><div className="variant-head"><div><b>{hfSelected.id}</b><div className="muted small">Choose a GGUF quantization</div></div></div><div className="variant-list">{variants.map(v=>{const rec=recommendation(variants,memory)===v.filename,f=fit(v.size,memory),id=`${hfSelected.id}:${v.filename}`,job=imports[id];return <div className={`variant-row ${rec?'recommended':''}`} key={v.filename}><div className="variant-main"><b>{v.quantization} {rec&&<span className="rec-pill">Best fit</span>}</b><small>{fmt(v.size)} · SHA {v.sha256?'available':'not exposed'}</small><small>{v.filename}</small>{job&&<div className={`task-state ${job.error?'error':job.done?'done':''}`}>{job.error||job.status} {job.percent!==undefined?`${job.percent.toFixed(1)}%`:''}</div>}</div><div><div className="variant-fit">{f.score}/100</div>{!job?.done&&<button className="variant-install" disabled={!!job&&!job.done} onClick={()=>importVariant(v)}>Import</button>}{job&&!job.done&&<button className="ghost" onClick={()=>invoke('cancel_hf_import',{importId:id})}>Cancel</button>}</div></div>})}</div></>:<div className="empty-card">Search and select a repository to inspect its GGUF files.</div>}</div></div></section></div></>}
 {tab==='developer'&&<div className="developer-grid"><section className="dev-intro"><div className="eyebrow">Developer Studio</div><h2>Local API without mystery.</h2><p className="muted">ModelDock keeps Ollama compatible. Advanced users can still integrate directly with the local runtime.</p><div className="dev-summary">Active engine: <b>{mode}</b><br/>Active model: <b>{selected||'none'}</b></div></section><section className="code-card"><div className="code-head"><b>JavaScript</b><button className="ghost" onClick={()=>navigator.clipboard.writeText(snippet)}>Copy</button></div><pre>{snippet}</pre></section></div>}
 </div></main></div>
}
