import {useEffect,useMemo,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {task} from './taskBus';
import './performance09.css';
type Mode='bundled'|'external';
type Model={name:string;size:number;details?:{parameter_size?:string;quantization_level?:string;family?:string}};
type Active={name?:string;size_vram?:number};
type Row={model:string;coldLoadMs:number;warmLoadMs:number;coldTokS:number;warmTokS:number;at:string};
const GB=1024**3,fmt=(n=0)=>n?`${(n/GB).toFixed(n>10*GB?1:2)} GB`:'—';
const api=(mode:Mode,method:string,path:string,body?:unknown)=>invoke<any>('ollama_json',{mode,method,path,body:body??null});
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
export default function CompareBench09({mode}:{mode:Mode}){
 const [models,setModels]=useState<Model[]>([]),[picked,setPicked]=useState<string[]>([]),[target,setTarget]=useState(''),[history,setHistory]=useState<number[]>([]),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[rows,setRows]=useState<Row[]>(()=>{try{return JSON.parse(localStorage.getItem('openguin-coldwarm')||'[]')}catch{return[]}});
 async function sample(){try{const[t,p]=await Promise.all([api(mode,'GET','/api/tags'),api(mode,'GET','/api/ps')]);const next=t.models??[];setModels(next);setTarget(v=>v||next[0]?.name||'');setHistory(h=>[...h,(p.models??[]).reduce((s:number,m:Active)=>s+(m.size_vram??0),0)].slice(-60))}catch(e){setStatus(String(e))}}
 useEffect(()=>{sample();const id=setInterval(()=>{if(!document.hidden)sample()},4000);return()=>clearInterval(id)},[mode]);
 const chosen=useMemo(()=>picked.map(n=>models.find(m=>m.name===n)).filter(Boolean) as Model[],[picked,models]);
 function toggle(n:string){setPicked(v=>v.includes(n)?v.filter(x=>x!==n):v.length<3?[...v,n]:v)}
 async function ensureUnloaded(model:string){let p=await api(mode,'GET','/api/ps');let resident=(p.models??[]).some((m:Active)=>m.name===model||m.name?.startsWith(`${model}:`));if(!resident)return;await sleep(350);p=await api(mode,'GET','/api/ps');resident=(p.models??[]).some((m:Active)=>m.name===model||m.name?.startsWith(`${model}:`));if(resident)throw new Error('Cold-start precondition failed: model is still resident after unload request.')}
 async function benchmark(){if(!target||busy)return;const id=`bench:coldwarm:${target}`;setBusy(true);setStatus('Cold start: unloading model…');task({id,title:`Cold / warm benchmark · ${target}`,source:'Observatory',detail:'Stage 1/5 · unloading model',state:'running',percent:8,progressKind:'stage'});try{await api(mode,'POST','/api/generate',{model:target,prompt:'',stream:false,keep_alive:0});task({id,title:`Cold / warm benchmark · ${target}`,source:'Observatory',detail:'Stage 2/5 · verifying cold-start precondition',state:'running',percent:20,progressKind:'stage'});await ensureUnloaded(target);const run=async()=>{const r=await api(mode,'POST','/api/generate',{model:target,prompt:'Reply with exactly: OK',stream:false,keep_alive:'10m',options:{num_predict:8,temperature:0,seed:42}});return{loadMs:(r.load_duration??0)/1e6,tokS:r.eval_duration&&r.eval_count?r.eval_count/(r.eval_duration/1e9):0}};setStatus('Measuring verified cold run…');task({id,title:`Cold / warm benchmark · ${target}`,source:'Observatory',detail:'Stage 3/5 · cold start measurement',state:'running',percent:38,progressKind:'stage'});const c=await run();setStatus('Measuring warm run…');task({id,title:`Cold / warm benchmark · ${target}`,source:'Observatory',detail:'Stage 4/5 · warm inference measurement',state:'running',percent:70,progressKind:'stage'});const w=await run();task({id,title:`Cold / warm benchmark · ${target}`,source:'Observatory',detail:'Stage 5/5 · saving benchmark',state:'running',percent:92,progressKind:'stage'});const row={model:target,coldLoadMs:c.loadMs,warmLoadMs:w.loadMs,coldTokS:c.tokS,warmTokS:w.tokS,at:new Date().toISOString()};setRows(v=>{const n=[row,...v].slice(0,20);localStorage.setItem('openguin-coldwarm',JSON.stringify(n));return n});setStatus(`Verified cold/warm pair · cold load ${c.loadMs.toFixed(0)} ms · warm load ${w.loadMs.toFixed(0)} ms`);task({id,title:`Cold / warm benchmark · ${target}`,source:'Observatory',detail:`Cold ${c.loadMs.toFixed(0)} ms · warm ${w.loadMs.toFixed(0)} ms`,state:'done',percent:100,progressKind:'stage'})}catch(e){setStatus(String(e));task({id,title:`Cold / warm benchmark · ${target}`,source:'Observatory',detail:String(e),state:'failed',percent:100,progressKind:'stage'})}finally{setBusy(false);sample()}}
 const max=Math.max(1,...history),points=history.map((v,i)=>`${10+i*580/Math.max(1,history.length-1)},${105-v/max*90}`).join(' '),latest=rows[0];
 const loadSaved=latest?Math.max(0,latest.coldLoadMs-latest.warmLoadMs):0,speedDelta=latest&&latest.coldTokS?((latest.warmTokS/latest.coldTokS)-1)*100:0;
 return <><div className="p09-grid"><section className="p09-card"><div className="p09-head"><div><span>MODEL COMPARATOR</span><h3>Side-by-side installed models</h3></div><small>{picked.length}/3</small></div><div className="p09-pills">{models.map(m=><button className={picked.includes(m.name)?'on':''} key={m.name} onClick={()=>toggle(m.name)}>{m.name}</button>)}</div>{chosen.length?<div className="p09-table"><div className="row head"><span>Model</span><span>Disk</span><span>Params</span><span>Quant</span><span>Family</span></div>{chosen.map(m=><div className="row" key={m.name}><b>{m.name}</b><span>{fmt(m.size)}</span><span>{m.details?.parameter_size||'—'}</span><span>{m.details?.quantization_level||'—'}</span><span>{m.details?.family||'—'}</span></div>)}</div>:<p className="p09-empty">Select up to three models to compare.</p>}</section><section className="p09-card"><div className="p09-head"><div><span>MEMORY HISTORY</span><h3>Runtime allocation trend</h3></div><small>60 samples · pauses when hidden</small></div>{history.length>1?<svg className="p09-spark" viewBox="0 0 600 120" role="img" aria-label="Runtime memory history"><line x1="10" y1="105" x2="590" y2="105"/><polyline points={points}/></svg>:<p className="p09-empty">Collecting samples…</p>}<div className="p09-context"><div><small>Current</small><b>{fmt(history.at(-1)??0)}</b></div><div><small>Peak</small><b>{fmt(Math.max(0,...history))}</b></div></div></section></div><section className="p09-card"><div className="p09-head"><div><span>COLD / WARM BENCHMARK</span><h3>Separate verified loading cost from steady-state inference</h3></div></div><div className="p09-benchbar"><select value={target} onChange={e=>setTarget(e.target.value)}>{models.map(m=><option key={m.name}>{m.name}</option>)}</select><button className="primary" disabled={busy||!target} onClick={benchmark}>{busy?'Benchmarking…':'Run controlled benchmark'}</button></div>{status&&<p className="p09-status">{status}</p>}{latest&&<div className="p09-context"><div><small>Latest warm-load saving</small><b>{loadSaved.toFixed(0)} ms</b></div><div><small>Warm decode delta</small><b>{`${speedDelta>=0?'+':''}${speedDelta.toFixed(1)}%`}</b></div></div>}{rows.length?<div className="p09-table"><div className="row head"><span>Model</span><span>Cold load</span><span>Warm load</span><span>Cold tok/s</span><span>Warm tok/s</span></div>{rows.map((r,i)=><div className="row" key={`${r.at}-${i}`}><b>{r.model}</b><span>{r.coldLoadMs.toFixed(0)} ms</span><span>{r.warmLoadMs.toFixed(0)} ms</span><span>{r.coldTokS.toFixed(1)}</span><span>{r.warmTokS.toFixed(1)}</span></div>)}</div>:<p className="p09-empty">No controlled benchmark runs yet.</p>}</section></>
}
