import {useEffect,useMemo,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import './performance09.css';
type Mode='bundled'|'external';
type Model={name:string;size:number;details?:{parameter_size?:string;quantization_level?:string;family?:string}};
type Active={size_vram?:number};
type Row={model:string;coldLoadMs:number;warmLoadMs:number;coldTokS:number;warmTokS:number;at:string};
const GB=1024**3,fmt=(n=0)=>n?`${(n/GB).toFixed(n>10*GB?1:2)} GB`:'—';
const api=(mode:Mode,method:string,path:string,body?:unknown)=>invoke<any>('ollama_json',{mode,method,path,body:body??null});
export default function CompareBench09({mode}:{mode:Mode}){
 const [models,setModels]=useState<Model[]>([]),[picked,setPicked]=useState<string[]>([]),[target,setTarget]=useState(''),[history,setHistory]=useState<number[]>([]),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[rows,setRows]=useState<Row[]>(()=>{try{return JSON.parse(localStorage.getItem('openguin-coldwarm')||'[]')}catch{return[]}});
 async function sample(){try{const[t,p]=await Promise.all([api(mode,'GET','/api/tags'),api(mode,'GET','/api/ps')]);setModels(t.models??[]);if(!target&&t.models?.[0])setTarget(t.models[0].name);setHistory(h=>[...h,(p.models??[]).reduce((s:number,m:Active)=>s+(m.size_vram??0),0)].slice(-60))}catch(e){setStatus(String(e))}}
 useEffect(()=>{sample();const id=setInterval(sample,2500);return()=>clearInterval(id)},[mode]);
 const chosen=useMemo(()=>picked.map(n=>models.find(m=>m.name===n)).filter(Boolean) as Model[],[picked,models]);
 function toggle(n:string){setPicked(v=>v.includes(n)?v.filter(x=>x!==n):v.length<3?[...v,n]:v)}
 async function benchmark(){if(!target||busy)return;setBusy(true);setStatus('Cold start: unloading model…');try{await api(mode,'POST','/api/generate',{model:target,prompt:'',stream:false,keep_alive:0});const run=async()=>{const r=await api(mode,'POST','/api/generate',{model:target,prompt:'Reply with exactly: OK',stream:false,keep_alive:'10m',options:{num_predict:8,temperature:0}});return{loadMs:(r.load_duration??0)/1e6,tokS:r.eval_duration&&r.eval_count?r.eval_count/(r.eval_duration/1e9):0}};setStatus('Measuring cold run…');const c=await run();setStatus('Measuring warm run…');const w=await run();const row={model:target,coldLoadMs:c.loadMs,warmLoadMs:w.loadMs,coldTokS:c.tokS,warmTokS:w.tokS,at:new Date().toISOString()};setRows(v=>{const n=[row,...v].slice(0,20);localStorage.setItem('openguin-coldwarm',JSON.stringify(n));return n});setStatus(`Done · cold load ${c.loadMs.toFixed(0)} ms · warm load ${w.loadMs.toFixed(0)} ms`)}catch(e){setStatus(String(e))}finally{setBusy(false);sample()}}
 const max=Math.max(1,...history),points=history.map((v,i)=>`${10+i*580/Math.max(1,history.length-1)},${105-v/max*90}`).join(' ');
 return <><div className="p09-grid"><section className="p09-card"><div className="p09-head"><div><span>MODEL COMPARATOR</span><h3>Side-by-side installed models</h3></div><small>{picked.length}/3</small></div><div className="p09-pills">{models.map(m=><button className={picked.includes(m.name)?'on':''} key={m.name} onClick={()=>toggle(m.name)}>{m.name}</button>)}</div>{chosen.length?<div className="p09-table"><div className="row head"><span>Model</span><span>Disk</span><span>Params</span><span>Quant</span><span>Family</span></div>{chosen.map(m=><div className="row" key={m.name}><b>{m.name}</b><span>{fmt(m.size)}</span><span>{m.details?.parameter_size||'—'}</span><span>{m.details?.quantization_level||'—'}</span><span>{m.details?.family||'—'}</span></div>)}</div>:<p className="p09-empty">Select up to three models to compare.</p>}</section><section className="p09-card"><div className="p09-head"><div><span>MEMORY HISTORY</span><h3>Runtime allocation trend</h3></div><small>60 samples</small></div>{history.length>1?<svg className="p09-spark" viewBox="0 0 600 120" role="img" aria-label="Runtime memory history"><line x1="10" y1="105" x2="590" y2="105"/><polyline points={points}/></svg>:<p className="p09-empty">Collecting samples…</p>}<div className="p09-context"><div><small>Current</small><b>{fmt(history.at(-1)??0)}</b></div><div><small>Peak</small><b>{fmt(Math.max(0,...history))}</b></div></div></section></div><section className="p09-card"><div className="p09-head"><div><span>COLD / WARM BENCHMARK</span><h3>Separate loading cost from steady-state inference</h3></div></div><div className="p09-benchbar"><select value={target} onChange={e=>setTarget(e.target.value)}>{models.map(m=><option key={m.name}>{m.name}</option>)}</select><button className="primary" disabled={busy||!target} onClick={benchmark}>{busy?'Benchmarking…':'Run controlled benchmark'}</button></div>{status&&<p className="p09-status">{status}</p>}{rows.length?<div className="p09-table"><div className="row head"><span>Model</span><span>Cold load</span><span>Warm load</span><span>Cold tok/s</span><span>Warm tok/s</span></div>{rows.map((r,i)=><div className="row" key={`${r.at}-${i}`}><b>{r.model}</b><span>{r.coldLoadMs.toFixed(0)} ms</span><span>{r.warmLoadMs.toFixed(0)} ms</span><span>{r.coldTokS.toFixed(1)}</span><span>{r.warmTokS.toFixed(1)}</span></div>)}</div>:<p className="p09-empty">No controlled benchmark runs yet.</p>}</section></>
}
